# Working with Pandas MultiIndex DataFrames

In [1]:
# The necessary imports for pandas and MultiIndex slicing
import pandas as pd
idx = pd.IndexSlice

## How to create a multiIndexed DataFrame from a dict of df's

##### Read in the data

In [3]:
df = pd.read_hdf('../propane_DMDS_23_12_2015.h5', key='processed/yields/RGA_TCD')
df[['800-1','800-2','850-2']].head()

                                   800-1      800-2      850-2
sheets    molecules
C_balance 1S/C2H2/c1-2/h1-2H    0.144047   0.238875   0.740284
          1S/C2H4/c1-2/h1-2H2  24.186368  24.169800  36.462024
          1S/C2H6/c1-2/h1-2H3   1.878542   1.877029   2.813672
          1S/CH4/h1H4          12.717481  12.755455  20.697376
          1S/CO/c1-2            0.075387   0.015377   0.057326

##### print some values

In [4]:
df.index.names

FrozenList(['sheets', 'molecules'])

In [5]:
df.index.get_level_values('sheets')

Index(['C_balance', 'C_balance', 'C_balance', 'C_balance', 'C_balance',
       'C_balance', 'C_balance', 'C_balance_after_C_norm',
       'C_balance_after_C_norm', 'C_balance_after_C_norm',
       ...
       'norm_yields_wet', 'norm_yields_wet', 'raw_yields', 'raw_yields',
       'raw_yields', 'raw_yields', 'raw_yields', 'raw_yields', 'raw_yields',
       'raw_yields'],
      dtype='object', name='sheets', length=160)

##### The index needs to be sorted to be able to select via `.loc`

In [6]:
df.sort_index(inplace=True)
df.loc[idx[:, '1S/C2H2/c1-2/h1-2H'],'800-1':'825-5'].head()

,,800-1,800-2,800-3,800-4,825-1,825-2,825-3,825-4,825-5
sheets,molecules,,,,,,,,,
C_balance,1S/C2H2/c1-2/h1-2H,0.144047,0.238875,0.230288,0.229780,0.235163,0.316089,0.327887,0.363288,0.408982
C_balance_after_C_norm,1S/C2H2/c1-2/h1-2H,0.138415,0.224567,0.222051,0.223555,0.223909,0.319118,0.333374,0.364905,0.396586
C_balance_norm,1S/C2H2/c1-2/h1-2H,0.137946,0.223882,0.221425,0.222797,0.223482,0.318261,0.333838,0.363766,0.395150
C_norm_yields,1S/C2H2/c1-2/h1-2H,0.150031,0.243413,0.240686,0.242317,0.242700,0.345900,0.361352,0.395529,0.429869
H_balance,1S/C2H2/c1-2/h1-2H,0.012089,0.020047,0.019326,0.019284,0.019736,0.026527,0.027517,0.030488,0.034323

##### Show the indices of the first index level

In [8]:
df.index.levels[0]

Index(['C_balance', 'C_balance_after_C_norm', 'C_balance_norm',
       'C_norm_yields', 'H_balance', 'H_balance_after_C_norm',
       'H_balance_norm', 'N_balance', 'N_balance_after_C_norm',
       'N_balance_norm', 'O_balance', 'O_balance_after_C_norm',
       'O_balance_norm', 'S_balance', 'S_balance_after_C_norm',
       'S_balance_norm', 'mol_perc', 'mol_perc_wet', 'norm_C_balance',
       'norm_yields', 'norm_yields_wet', 'raw_yields'],
      dtype='object', name='sheets')

Equivalent command

In [9]:
df.index.get_level_values('sheets').unique()

Index(['C_balance', 'C_balance_after_C_norm', 'C_balance_norm',
       'C_norm_yields', 'H_balance', 'H_balance_after_C_norm',
       'H_balance_norm', 'N_balance', 'N_balance_after_C_norm',
       'N_balance_norm', 'O_balance', 'O_balance_after_C_norm',
       'O_balance_norm', 'S_balance', 'S_balance_after_C_norm',
       'S_balance_norm', 'mol_perc', 'mol_perc_wet', 'norm_C_balance',
       'norm_yields', 'norm_yields_wet', 'raw_yields'],
      dtype='object', name='sheets')

##### Example how to change the index (lowercase letters)

In [14]:
df.index.set_levels(df.index.levels[1].map(str.lower), level='molecules', inplace=True)
df.loc[idx['C_balance', :],'800-1':'825-5'].head()

                                   800-1      800-2      800-3      800-4  \
sheets    molecules
C_balance 1s/c2h2/c1-2/h1-2h    0.144047   0.238875   0.230288   0.229780
          1s/c2h4/c1-2/h1-2h2  24.186368  24.169800  23.572412  23.420912
          1s/c2h6/c1-2/h1-2h3   1.878542   1.877029   1.831825   1.819332
          1s/ch4/h1h4          12.717481  12.755455  12.430975  12.337525
          1s/co/c1-2            0.075387   0.015377   0.015222   0.008540

                                   825-1      825-2      825-3      825-4  \
sheets    molecules
C_balance 1s/c2h2/c1-2/h1-2h    0.235163   0.316089   0.327887   0.363288
          1s/c2h4/c1-2/h1-2h2  24.406451  26.077378  26.308444  27.433185
          1s/c2h6/c1-2/h1-2h3   1.896352   2.019069   2.038554   2.142274
          1s/ch4/h1h4          12.893903  13.935782  14.165900  14.858289
          1s/co/c1-2            0.014557   0.014116   0.011494   0.010736

                                   825-5
sheets    molecules
C_balance 1s/c2h2/c1-2/h1-2h    0.408982
          1s/c2h4/c1-2/h1-2h2  29.033529
          1s/c2h6/c1-2/h1-2h3   2.271752
          1s/ch4/h1h4          15.746223
          1s/co/c1-2            0.014048

### How to slice the first index

In [36]:
store = pd.HDFStore('../propane_DMDS_23_12_2015.h5')
df = store['processed/yields/total'].loc[idx['C_norm_yields', :]]
df.head()

,800-1,800-2,800-3,800-4,825-1,825-2,825-3,825-4,825-5,850-1,850-2,850-3,850-4,875-1,875-2,875-3,875-4
molecules,,,,,,,,,,,,,,,,,
"1S/C10H10/c1-8-6-7-9-4-2-3-5-10(8)9/h2-8H,1H3",0.000000,0.000000,0.000000,0.000000,0.010504,0.012037,0.012322,0.012769,0.013063,0.000000,0.000000,0.000000,0.000000,0.027131,0.027800,0.028004,0.028292
"1S/C10H14/c1-2-3-7-10-8-5-4-6-9-10/h4-6,8-9H,2-3,7H2,1H3",0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.066893,0.066861,0.066363,0.066286,0.074827,0.076674,0.077236,0.078032
"1S/C10H22/c1-3-5-7-9-10-8-6-4-2/h3-10H2,1-2H3",0.000000,0.000000,0.000000,0.000000,0.017503,0.020059,0.020535,0.021278,0.021769,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1S/C10H8/c1-2-6-10-8-4-3-7-9(10)5-1/h1-8H,0.000000,0.000000,0.000000,0.000000,0.020751,0.023780,0.024344,0.025226,0.025808,0.634409,0.634108,0.629384,0.628661,0.143755,0.147302,0.148382,0.149911
1S/C2H2/c1-2/h1-2H,0.150031,0.243413,0.240686,0.242317,0.242700,0.345900,0.361352,0.395529,0.429869,0.648284,0.714347,0.749089,0.774987,0.972801,1.139489,1.199108,1.246302

##### Equivalent

In [39]:
store = pd.HDFStore('../propane_DMDS_23_12_2015.h5')
df = store['processed/yields/total'].xs('C_norm_yields')
df.head()

,800-1,800-2,800-3,800-4,825-1,825-2,825-3,825-4,825-5,850-1,850-2,850-3,850-4,875-1,875-2,875-3,875-4
molecules,,,,,,,,,,,,,,,,,
"1S/C10H10/c1-8-6-7-9-4-2-3-5-10(8)9/h2-8H,1H3",0.000000,0.000000,0.000000,0.000000,0.010504,0.012037,0.012322,0.012769,0.013063,0.000000,0.000000,0.000000,0.000000,0.027131,0.027800,0.028004,0.028292
"1S/C10H14/c1-2-3-7-10-8-5-4-6-9-10/h4-6,8-9H,2-3,7H2,1H3",0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.066893,0.066861,0.066363,0.066286,0.074827,0.076674,0.077236,0.078032
"1S/C10H22/c1-3-5-7-9-10-8-6-4-2/h3-10H2,1-2H3",0.000000,0.000000,0.000000,0.000000,0.017503,0.020059,0.020535,0.021278,0.021769,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1S/C10H8/c1-2-6-10-8-4-3-7-9(10)5-1/h1-8H,0.000000,0.000000,0.000000,0.000000,0.020751,0.023780,0.024344,0.025226,0.025808,0.634409,0.634108,0.629384,0.628661,0.143755,0.147302,0.148382,0.149911
1S/C2H2/c1-2/h1-2H,0.150031,0.243413,0.240686,0.242317,0.242700,0.345900,0.361352,0.395529,0.429869,0.648284,0.714347,0.749089,0.774987,0.972801,1.139489,1.199108,1.246302

##### Add additional column with the sum of the C and c

In [15]:
df['Catoms'] = df.index.get_level_values('molecules').map(lambda x: str(x).count('C') + str(x).count('c'))

##### Show the sorted results based on above extra column

In [17]:
small_df = df.loc[idx['C_balance', :]].sort_values('Catoms', axis=0).drop(labels='Catoms', axis=1)
small_df

,800-1,800-2,800-3,800-4,825-1,825-2,825-3,825-4,825-5,850-1,850-2,850-3,850-4,875-1,875-2,875-3,875-4
molecules,,,,,,,,,,,,,,,,,
1s/h2/h1h,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1s/ch4/h1h4,12.717481,12.755455,12.430975,12.337525,12.893903,13.935782,14.165900,14.858289,15.746223,20.747523,20.697376,20.228714,20.503127,23.077182,23.498674,23.058292,23.338320
1s/c2h2/c1-2/h1-2h,0.144047,0.238875,0.230288,0.229780,0.235163,0.316089,0.327887,0.363288,0.408982,0.673130,0.740284,0.764404,0.802481,1.004365,1.169102,1.198423,1.247862
1s/c2h4/c1-2/h1-2h2,24.186368,24.169800,23.572412,23.420912,24.406451,26.077378,26.308444,27.433185,29.033529,36.572440,36.462024,35.708812,36.297821,38.800494,39.085638,38.178437,38.382687
1s/c2h6/c1-2/h1-2h3,1.878542,1.877029,1.831825,1.819332,1.896352,2.019069,2.038554,2.142274,2.271752,2.799556,2.813672,2.720217,2.762514,2.855755,2.825095,2.745192,2.765386
1s/co/c1-2,0.075387,0.015377,0.015222,0.008540,0.014557,0.014116,0.011494,0.010736,0.014048,0.060417,0.057326,0.047321,0.037842,0.044604,0.039788,0.049336,0.040109
1s/co2/c2-1-3,0.014030,0.003034,0.002573,0.004869,0.008976,0.001421,0.004236,0.001802,0.001211,0.005027,0.002646,0.003783,0.002805,0.001630,0.000834,0.000782,0.000395

### Create an overview DataFrame

In [34]:
keys = ['RGA_FID', 'RGA_TCD', 'sums']
dfs = [pd.read_hdf('../propane_DMDS_23_12_2015.h5', key='processed/yields/{}'.format(key)) for key in keys]

In [21]:
import numpy as np
from functools import reduce
sheets = reduce(np.union1d, [df.index.get_level_values('sheets') for df in dfs])
sheets

array(['C_balance', 'C_balance_after_C_norm', 'C_balance_norm',
       'C_norm_yields', 'H_balance', 'H_balance_after_C_norm',
       'H_balance_norm', 'N_balance', 'N_balance_after_C_norm',
       'N_balance_norm', 'O_balance', 'O_balance_after_C_norm',
       'O_balance_norm', 'S_balance', 'S_balance_after_C_norm',
       'S_balance_norm', 'mol_perc', 'mol_perc_wet', 'norm_C_balance',
       'norm_yields', 'norm_yields_wet', 'raw_yields'], dtype=object)

In [35]:
for sheetname in sheets:
    joined_data = pd.concat([df.loc[idx[sheetname, :]] for df in dfs] , axis=0)
joined_data.tail(5)

,800-1,800-2,800-3,800-4,825-1,825-2,825-3,825-4,825-5,850-1,850-2,850-3,850-4,875-1,875-2,875-3,875-4
molecules,,,,,,,,,,,,,,,,,
1S/H2/h1H,1.255652,1.434195,1.374433,1.422680,1.430424,1.480294,1.065938,1.546873,1.663433,1.406773,1.297471,2.013221,2.038784,1.941219,2.228533,2.186370,2.200738
1S/N2/c1-2,38.461538,38.461538,38.461538,38.461538,38.461538,38.461538,38.461538,38.461538,38.461538,38.461538,38.461538,38.461538,38.461538,38.461538,38.461538,38.461538,38.461538
C4,102.850714,105.119852,102.466088,101.609222,102.183909,96.028986,94.874579,96.362194,99.784617,100.884971,100.559828,99.810190,101.265060,100.268119,99.652539,97.017770,97.083930
C5,1.572108,1.576803,1.536691,1.525139,3.042709,3.288573,3.342876,3.506266,3.715801,11.140305,11.113379,10.861733,11.009078,11.786837,12.002117,11.777189,11.920216
Total,104.422822,106.696655,104.002779,103.134361,105.226618,99.317558,98.217455,99.868460,103.500419,112.025276,111.673207,110.671923,112.274137,112.054956,111.654657,108.794959,109.004146

In [30]:
import numpy as np

In [31]:
a = pd.DataFrame(np.random.rand(3,3))
b = pd.DataFrame(np.random.rand(3,3))
c = pd.DataFrame(np.random.rand(3,3))

dct = {'a': a, 'b': b, 'c': c}
joined = pd.concat(dct)
joined

            0         1         2
a 0  0.627494  0.072274  0.537623
  1  0.382320  0.671545  0.588424
  2  0.173387  0.457166  0.504858
b 0  0.069516  0.345199  0.115348
  1  0.572760  0.519037  0.898574
  2  0.627478  0.367608  0.625081
c 0  0.816646  0.916364  0.734095
  1  0.297209  0.317491  0.756556
  2  0.744876  0.380615  0.294683

In [32]:
joined.loc[idx['a', :]]

          0         1         2
0  0.627494  0.072274  0.537623
1  0.382320  0.671545  0.588424
2  0.173387  0.457166  0.504858